sudo: required
dist: bionic
os: linux
group: stable
language: node_js
node_js: 16.14.0

before_install:
  - sudo apt-get update
  - sudo apt-get install python2.7 git -y
  - npm install -g node-gyp

install:
  - cd ~/abgp && npm install && npm run tsc:build
  - cd ~/implementations/crypto/bnelliptic && npm install && npm run build_dist
  - cd ~/implementations/crypto/plain && npm install && npm run build_dist
  - cd ~/implementations/node/rpc && npm install && npm run build_dist
  - cd ~/implementations/node/tcp && npm install && npm run build_dist
  - cd ~/implementations/storage/plain && npm install && npm run build_dist

script:
  - cd ~/abgp && mkdir dump && npm test

notifications:
  email: false

cache:
  directories:
    - node_modules